### PR TITLE
update - exclude non updated values

### PR DESCRIPTION
**Pull request by dzejkob-b**
Sending zeroes in attributes which is not specified in request might cause disastrous consequences. According to specification and official recommendations unfilled attributies should not be present in the soap xml - without this update i see them in last request.

### CODE REVIEW

**Comment by sieberlukas** [comment]
Some attributes are required and must be in the request. (Header: uuid_zpravy, dat_odesl, prvni_zaslan
i ; Body: dic_popl, id_provoz, id_pokl, porad_cis, dat_trzby, celk_trzba, rezim)

**Comment by tvape** [comment]
@dzejkob-b could you give me an example of "disastrous consequences" please? What specific parameter do you mean?

According to the specification all optional parameters **can** be omitted, however, they **don't have to be** omitted.

Which means that especially the amount parameters (eg. dan1) can be set as **zero** or omitted. If they are omitted they are regarded as **empty** or **undefined**, not zero.

**Comment by sieberlukas** [comment]
Attribute dic_ poverujiciho is not required.

**Comment by dzejkob-b** [comment]
Have some real scenario with my implementation in other language - the api consumer used "zakl_dan3" with some value and "dan3" missing. But agree, it cannot happen, when all values are zeroes - but at least is  misleading while debugging or reading logs - zero carry information, that is zero of something.

+ updated from boolean to testing null + only optional numeric values

**Comment by sieberlukas** [comment]
Attribute dic_ poverujiciho is not required.

Update to public $dic_poverujiciho = null;

**Comment by dzejkob-b** [comment]
Well see for php is null implict value - and SoapClient automatically omits them - so update is much simplified.

**Comment by stromek** [comment]
At time 40:20 in this video https://youtu.be/DgFH6tJhc6g?t=2420 you should omits values, that are not relevant. Zero values are invalid.

**Comment by tvape** [comment]
The woman herself was not clear about "shouldn't" or "mustn't".

I could not find any reference in the EET specification saying that 
irrelevant parameters MUST be ommited. Could you please send me a link 
to that info in the specification?


------ Původní zpráva ------
Od: "stromek" <notifications@github.com>
Komu: "ondrejnov/eet" <eet@noreply.github.com>
Kopie: "Petr Tvaroha" <ptvaroha@gmail.com>; "Comment" 
<comment@noreply.github.com>
Odesláno: 28.02.2017 11:08:42
Předmět: Re: [ondrejnov/eet] update - exclude non updated values (#37)

**Comment by alexadavid** [comment]
I've just found http://www.etrzby.cz/assets/cs/prilohy/EET_popis_rozhrani_v3.1.1.pdf, section 3.3.2

```
)** Položky označené jako povinné musí být vyplněny v každé datové zprávě. Položky označené jako nepovinné musí být vyplněny, pokud jsou k evidované tržbě relevantní (např. plátci DPH musí mít vyplněny položky o DPH, které jsou relevantní k tržbě). Nejsou-li nepovinné položky uvedeny, jsou považovány za prázdné. Položky s prázdnou hodnotou jsou v XML zprávě nepřípustné.
```

+ in section 3.3.3.11 - ommited param is different from 0 value

**Comment by tvape** [comment]
@alexadavid On the video, on the projection screen there is stated "(ani vyplněny nulou)" but this is not stated in the specification. The specification says that **empty** parameters are not acceptable.
Parameters with **zero** are **not** empty and that's why they are IMO acceptable.

**Comment by GenaritoBike** [comment]
Hi, 
@tvape, @alexadavid He's right. Here is an official document with examples. Look at the example "Příklad 1 – Služba s jednou sazbou DPH"

http://www.etrzby.cz/assets/cs/prilohy/Priklady_datove_zpravy.pdf

**Comment by alexadavid** [comment]
ok, documnet from @GenaritoBike, section D...
...
_nesmí být uvedeny (ani vyplněny nulou) takové nepovinné položky dle § 19 odst. 2 ZoET,
které k dané tržbě nejsou relevantní._

**Comment by demontefacto** [comment]
/...nepovinné... Povinné položky nesmí zůstat prázdné. Není tohle dané 
strukturou WSDL/XSD? Pokud je položka povinná a nebude uvedena, taková 
datová zpráva bude brána jako nevalidní
/


Dne 28.2.2017 v 12:00 David Alexa napsal(a):

**Comment by tvape** [comment]
Well, I think it would be better not to send them, however, it is only a document with examples, it is not the specification itself.

**Comment by ondrejnov** [comment]
presvedcili jste me, uprava je v masteru

**Pull request closed without merging**
